// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2Wt3lhOuhLiuIoZimcNZidBJRgrILKo',
    appId: '1:864185885257:web:780b4d952e45894c8a9598',
    messagingSenderId: '864185885257',
    projectId: 'ipix-machinetest',
    authDomain: 'ipix-machinetest.firebaseapp.com',
    storageBucket: 'ipix-machinetest.appspot.com',
    measurementId: 'G-4YCYR80QEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCPf94Xnr0JiP5uXnPGaSs1_YaZ4YsPs',
    appId: '1:864185885257:android:957c6bf2a17e9f1e8a9598',
    messagingSenderId: '864185885257',
    projectId: 'ipix-machinetest',
    storageBucket: 'ipix-machinetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt57_Gh2fyvth5yecwsK25LfK0wDMMCxk',
    appId: '1:864185885257:ios:4bc2ae1c0952416a8a9598',
    messagingSenderId: '864185885257',
    projectId: 'ipix-machinetest',
    storageBucket: 'ipix-machinetest.appspot.com',
    iosBundleId: 'com.example.machineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt57_Gh2fyvth5yecwsK25LfK0wDMMCxk',
    appId: '1:864185885257:ios:a015171962c9e7ce8a9598',
    messagingSenderId: '864185885257',
    projectId: 'ipix-machinetest',
    storageBucket: 'ipix-machinetest.appspot.com',
    iosBundleId: 'com.example.machineTest.RunnerTests',
  );
}
